[project]
name = "redis-memurai-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "cyadriene@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "redis>=8.1.0",
]

[project.scripts]
redis-memurai-practice = "redis_memurai_practice:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
